VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICFormPhysicsEx"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Sub init(ByRef core As CFormPhysics, Optional ByRef params = Empty)
End Sub
Public Property Get CreateInstance() As ICFormPhysicsEx
End Property
Public Sub Terminate()
End Sub
