VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICFormPhysicsEf"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Sub init(ByRef targetGL As OpenGL)
End Sub
Public Property Get CreateInstance() As ICFormPhysicsEf
End Property
Public Sub Render(ByRef x As Double, ByRef y As Double, ByRef dt As Long, ByRef v As Double)
End Sub
Public Sub Reset(ByRef cx As Double, ByRef cy As Double, ByRef ddmg As Double, Optional ByRef hw As Double = 0, Optional ByRef hh As Double = 0)
End Sub
